// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const tabs: string;
export const line: string;
export const selected: string;
export const btn_category: string;
